# Generated by Django 2.2.7 on 2019-11-08 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoastandRoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boastorroast', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('upordown', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prideorhide', models.BooleanField(default=True)),
            ],
        ),
    ]
