# Generated by Django 2.2.7 on 2019-11-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boastandroast',
            old_name='boastorroast',
            new_name='boast',
        ),
    ]
