# Generated by Django 2.2.7 on 2019-11-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_post', '0002_auto_20191111_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastandroast',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
