# Generated by Django 3.0.1 on 2019-12-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_post', '0004_remove_boastandroast_prideorhide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boastandroast',
            old_name='upordown',
            new_name='downvote',
        ),
        migrations.AddField(
            model_name='boastandroast',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
